spring:
  application:
    name: oauth2-authorization
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
server:
  address: 0.0.0.0
  port: 10030

liquibase:
  change-log: classpath:changelog/master.xml
